/*
 * emoji.js
 * A curated set of common GitHub emoji shortcodes -> unicode, for the emoji
 * picker. Inserting the unicode glyph keeps the editor WYSIWYG and renders on
 * GitHub too. Exposed as window.EmojiData (array of { code, char, keywords }).
 */
(function () {
  "use strict";

  // [shortcode, char, extra keywords]
  const raw = [
    ["rocket", "🚀", "launch ship deploy"],
    ["sparkles", "✨", "shine new"],
    ["tada", "🎉", "party celebrate release"],
    ["fire", "🔥", "hot lit"],
    ["star", "⭐", "favorite"],
    ["star2", "🌟", "glow"],
    ["zap", "⚡", "fast bolt performance"],
    ["boom", "💥", "collision"],
    ["100", "💯", "hundred perfect"],
    ["white_check_mark", "✅", "done check ok"],
    ["heavy_check_mark", "✔️", "done tick"],
    ["x", "❌", "no cross fail"],
    ["warning", "⚠️", "caution alert"],
    ["bug", "🐛", "issue defect"],
    ["wrench", "🔧", "fix tool config"],
    ["hammer", "🔨", "build tool"],
    ["hammer_and_wrench", "🛠️", "tools build"],
    ["gear", "⚙️", "settings config"],
    ["package", "📦", "box dependency npm"],
    ["books", "📚", "docs library"],
    ["book", "📖", "docs readme"],
    ["memo", "📝", "note write docs"],
    ["pencil2", "✏️", "edit write"],
    ["clipboard", "📋", "list copy"],
    ["bulb", "💡", "idea tip"],
    ["bookmark", "🔖", "tag version"],
    ["label", "🏷️", "tag"],
    ["link", "🔗", "url"],
    ["paperclip", "📎", "attach"],
    ["lock", "🔒", "secure private"],
    ["unlock", "🔓", "open"],
    ["key", "🔑", "secret auth"],
    ["shield", "🛡️", "security protect"],
    ["mag", "🔍", "search find"],
    ["chart_with_upwards_trend", "📈", "stats growth"],
    ["bar_chart", "📊", "stats analytics"],
    ["heavy_plus_sign", "➕", "add new"],
    ["heavy_minus_sign", "➖", "remove"],
    ["arrow_up", "⬆️", "top up"],
    ["arrow_down", "⬇️", "down"],
    ["recycle", "♻️", "refactor reuse"],
    ["construction", "🚧", "wip progress"],
    ["hourglass", "⏳", "wait pending"],
    ["alarm_clock", "⏰", "time"],
    ["calendar", "📅", "date schedule"],
    ["pushpin", "📌", "pin important"],
    ["dart", "🎯", "target goal"],
    ["trophy", "🏆", "win award"],
    ["medal", "🏅", "award"],
    ["crown", "👑", "best king"],
    ["gem", "💎", "quality premium"],
    ["thumbsup", "👍", "+1 like good"],
    ["thumbsdown", "👎", "-1 dislike"],
    ["clap", "👏", "applause nice"],
    ["raised_hands", "🙌", "celebrate praise"],
    ["muscle", "💪", "strong power"],
    ["point_right", "👉", "this direction"],
    ["wave", "👋", "hello hi bye"],
    ["handshake", "🤝", "deal agree contribute"],
    ["pray", "🙏", "thanks please"],
    ["eyes", "👀", "look review watch"],
    ["brain", "🧠", "smart think"],
    ["robot", "🤖", "bot ai automation"],
    ["alien", "👽", "ufo"],
    ["ghost", "👻", "boo"],
    ["skull", "💀", "dead fatal"],
    ["poop", "💩", "bad crap"],
    ["smile", "😄", "happy"],
    ["grin", "😁", "happy"],
    ["joy", "😂", "laugh lol"],
    ["wink", "😉", "joke"],
    ["thinking", "🤔", "hmm consider"],
    ["sunglasses", "😎", "cool"],
    ["sweat_smile", "😅", "phew"],
    ["cry", "😢", "sad"],
    ["scream", "😱", "shock"],
    ["heart", "❤️", "love like"],
    ["orange_heart", "🧡", "love"],
    ["yellow_heart", "💛", "love"],
    ["green_heart", "💚", "love"],
    ["blue_heart", "💙", "love"],
    ["purple_heart", "💜", "love"],
    ["broken_heart", "💔", "sad breakup"],
    ["computer", "💻", "laptop dev code"],
    ["desktop_computer", "🖥️", "pc"],
    ["keyboard", "⌨️", "type"],
    ["floppy_disk", "💾", "save"],
    ["cd", "💿", "disc"],
    ["battery", "🔋", "power"],
    ["electric_plug", "🔌", "power connect"],
    ["satellite", "📡", "network signal"],
    ["globe_with_meridians", "🌐", "web internet i18n"],
    ["cloud", "☁️", "cloud server"],
    ["zap2", "🌩️", "storm"],
    ["snowflake", "❄️", "freeze cold"],
    ["droplet", "💧", "water"],
    ["ocean", "🌊", "wave"],
    ["seedling", "🌱", "grow new start"],
    ["evergreen_tree", "🌲", "tree"],
    ["four_leaf_clover", "🍀", "luck"],
    ["sun", "☀️", "light day"],
    ["moon", "🌙", "night dark"],
    ["rainbow", "🌈", "colorful pride"],
    ["coffee", "☕", "break caffeine"],
    ["beer", "🍺", "drink cheers"],
    ["pizza", "🍕", "food"],
    ["hamburger", "🍔", "food"],
    ["cake", "🍰", "dessert birthday"],
    ["car", "🚗", "drive"],
    ["airplane", "✈️", "travel deploy ship"],
    ["ship", "🚢", "deploy release"],
    ["anchor", "⚓", "stable"],
    ["compass", "🧭", "navigate direction"],
    ["world_map", "🗺️", "map roadmap"],
    ["telescope", "🔭", "explore vision"],
    ["microscope", "🔬", "test research"],
    ["test_tube", "🧪", "test experiment"],
    ["dna", "🧬", "science"],
    ["magnet", "🧲", "attract"],
    ["balance_scale", "⚖️", "license law"],
    ["scroll", "📜", "license doc"],
    ["page_facing_up", "📄", "file doc"],
    ["file_folder", "📁", "folder directory"],
    ["open_file_folder", "📂", "folder open"],
    ["card_index_dividers", "🗂️", "organize"],
    ["inbox_tray", "📥", "download import"],
    ["outbox_tray", "📤", "upload export"],
    ["envelope", "✉️", "email contact"],
    ["email", "📧", "mail contact"],
    ["speech_balloon", "💬", "comment chat"],
    ["bell", "🔔", "notify alert"],
    ["megaphone", "📣", "announce"],
    ["loudspeaker", "📢", "announce"],
    ["mute", "🔇", "silent"],
    ["musical_note", "🎵", "music sound"],
    ["art", "🎨", "design style ui"],
    ["camera", "📷", "photo screenshot"],
    ["movie_camera", "🎥", "video record"],
    ["clapper", "🎬", "action video"],
    ["video_game", "🎮", "game play"],
    ["dice", "🎲", "random game"],
    ["jigsaw", "🧩", "plugin module piece"],
    ["building_construction", "🏗️", "build wip"],
    ["office", "🏢", "company enterprise"],
    ["house", "🏠", "home"],
    ["flag_checkered", "🏁", "finish start race"],
    ["triangular_flag_on_post", "🚩", "flag milestone"],
    ["no_entry", "⛔", "blocked forbidden"],
    ["stop_sign", "🛑", "stop halt"],
    ["recycle2", "🔁", "loop repeat"],
    ["arrows_counterclockwise", "🔄", "sync refresh"],
    ["ok_hand", "👌", "ok good"],
    ["question", "❓", "help unknown"],
    ["exclamation", "❗", "important"],
    ["information_source", "ℹ️", "info"],
    ["bangbang", "‼️", "urgent"],
    ["heavy_dollar_sign", "💲", "money cost"],
    ["moneybag", "💰", "money funding"],
    ["credit_card", "💳", "pay"],
    ["gift", "🎁", "present release"],
    ["balloon", "🎈", "party"],
    ["confetti_ball", "🎊", "celebrate"],
  ];

  window.EmojiData = raw.map(function (r) {
    return { code: r[0], char: r[1], keywords: r[0] + " " + (r[2] || "") };
  });
})();
